### ISSUE TITLE
using defaults for variables

### ISSUE THREAD

**Issue by lucascollino** [shyiko/kubetpl#10]
Hi, in the README it's mentioned:

"Fail-fast defaults (all variables must be given a value (unless explicitly marked optional))."

How do I mark a variable optional? Can't find it in the docs.

**Comment by shyiko** [comment]
It depends on a template flavor (syntax). 
For instance, `REPLICAS` is given `1` as a default value in [template kind](https://github.com/shyiko/kubetpl#template-kind) example
```
...
parameters:
- name: REPLICAS
  value: 1
...
```

Currently, there is no way to mark variable optional in case of [$](https://github.com/shyiko/kubetpl#template-flavors) (`$VAR` / `${VAR}`) (a.k.a. a safer version of envsubst). Having a `-i staging.env` file with all variables given explicit values proved to be just easier to maintain. BUT. We could add a support for [${VAR-default}, ${VAR:-default}](https://stackoverflow.com/a/26899206/482225) if enough people are interested.

**Comment by tgropper** [comment]
Hi, @shyiko. What about `go-template`?  
I'm trying to achieve something like this:

```yml
...
  replicas: {{ default 1 .REPLICAS }}
...
```

It looks like it's supported by [sprig](http://masterminds.github.io/sprig/defaults.html).

Thanks!

**Comment by shyiko** [comment]
Hi Tomás.

The reason `{{ default 1 .REPLICAS }}` isn't working is [missingkey=error](https://github.com/shyiko/kubetpl/blob/master/engine/go.go#L19). Basically, whenever variable is referenced via .VAR VAR must be defined or an error will be raised (fail-fast). 

You can either test whether variable is set with [def](https://github.com/shyiko/kubetpl/blob/master/engine/go.go#L34)
```yaml
...
  replicas: {{ if def . "VAR" }}{{ .VAR }}{{ else }}1{{ end }}
...
```
or use [default + pluck](http://masterminds.github.io/sprig/dicts.html#pluck) (from sprig)
```yaml
...
  replicas: {{ default 1 (pluck "VAR" . | first) }}
...
```
Both approaches feel a little bit to verbose and so it might be a good idea [to add a dedicated helper function]( https://github.com/shyiko/kubetpl/blob/master/engine/go.go#L33) (say `defval`) to simplify things to `{{ defval 1 . "VAR" }}`.

**Comment by shyiko** [comment]
@tgropper could you describe your use-case in more detail? I'm not against `--fail-fast=false`, it's just we might be able to come up with a better solution.

**Comment by tgropper** [comment]
I think there are three different scenarios:  
1. **fail-fast**: fail if any variable is missing.  
This is the current default behavior.
2. **replace the missing variable with empty**: if one variable is missing, then replace the placeholder with empty.  
Now you can make this possible using `go-template` with conditionals like you explained earlier.
3. **leave the placeholder**: if one variable is missing, don't do anything (with that variable).
This cannot be done (at least as I can see). We wanna use this feature to apply partial renders, because our CI/CD pipeline knows about different variables (image version, namespace, environment to be deployed, etc) in different stages.  

I know there are hundreds of other workarounds, but I don't see why it can't be a `kubetpl` feature. Unless there's any restriction with any template flavor.

What's the behavior of [`.Parse()`](https://github.com/shyiko/kubetpl/blob/master/engine/go.go#L19) if I don't set `"missingkey=error"`?

**Comment by shyiko** [comment]
Alright, guys. 
I believe changes introduced in [0.8.0](https://github.com/shyiko/kubetpl/blob/master/CHANGELOG.md#080---2018-09-28) should cover all the scenarios mentioned above:

> default value/fallback

--synatx=$: `# kubetpl:set:REPLICAS=1` (see CHANGELOG.md/README.md)
--syntax=go-template: `{{ get "REPLICAS" 1 }}` or `{{ if isset "REPLICAS" }}{{ .REPLICAS }}{{ else }}1{{ end }}`
--synatx=template-kind: `parameters: [{name: REPLICAS, value: 1}]`

> leave the placeholder

`kubetpl render ... --ignore-unset`.

Let me know if you have any further questions/suggestions.

**Comment by aditanase** [comment]
Pitching in as I went through all the steps above and I still feel that we're missing something if we don't add a flag for `missingkey=error`. Some problems also come from the fact that you're assuming env-style, flat variables even in go templates.

In summary, I feel like I can't use much of the value introduced by go templates and sprig.

Here's my use case. I am trying to implement a vey simple inventory with global settings and layered overrides, per component.
```
defaults.yaml:
---
containerLimits:
  cpu: 2
  memory: 2Gi

defaults.prod.yaml:
---
containerLimits:
  cpu: 4
  memory: 4Gi

componentA:
  containerLimits:
    cpu: 8
    memory: 8Gi
```

In the deployment template, here's a simple snippet that doesn't work if all the values are missing (but works if I remove the `missingkey=error` option):
```
{{ with default .containerLimits . componentA.containerLimits }}
resources:
  limits:
    cpu: {{ .cpu }}
    memory: {{ .memory }}
{{ end }}
```

I honestly have no idea how to assemble the same logic with `get`. For example, none of these work:
```
{{ get "componentA" false | get "containerLimits" }} // get is global, doesn't seem to use the dot context
{{ get "componentA.containerLimits" false }} // assumes single level
```

Finally, even with the flag disabled, I can't use any of the dict functions in sprig: `pluck`, 'merge' etc all fail with: `... wrong type for value; expected map[string]interface {}; got map[interface {}]interface {}`
I'm assuming this is also related to how you're loading the values in the data map, correct?

**Comment by aditanase** [comment]
Here's a quick prototype that fixes both issues (for me)
https://github.com/shyiko/kubetpl/compare/master...aditanase:test-yaml?expand=1

Code for 2nd issue copied from here:
https://github.com/go-yaml/yaml/issues/139

**Comment by aditanase** [comment]
@shyiko did you get a chance to review this?

**Comment by shyiko** [comment]
Hey @aditanase. Sorry for the delay. 

> ... you're assuming env-style, flat variables even in go templates ...

This is intentional. 
By keeping config files flat we ensure that
* operations are predictable/easy to reason about. Imagine you have `defaults.yaml` with `a: {b: {c1: [d, e, f]}}`. What should be the end result of `kubetpl render -i defaults.yaml -i staging.yaml --set a.b='{c1: [g]}' ...`, where staging.yaml is `a: {b: [{c2: [d, e, f]}]}` (or `a: {b: {c1: [a]}}`)? When do we "merge" and when do we "override"?
* .env (https://12factor.net/config) and .json/.yaml can be used interchangeably
* people tend to over-engineer stuff when given too much freedom (I've seen projects with configs 10 level deep for no reason). Flat structure helps with the abuse.
* CLI/API is as simple as possible

A few recommendations: 
* try not to use go-template|s (prefer [$VAR](https://github.com/shyiko/kubetpl#-shell)) unless you need if/for/etc, e.g.
```yaml
...
  template:
    spec:
{{ if isset "TOLERATION" }}
      tolerations:
      - key: "node-role.k8s.domain.com/dedicated-for"
        operator: Equal
        value: {{.TOLERATION}}
{{ end }}
...
```
```yaml
{{ range _, $domain := splitList "," .FQDNS }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $domain }}
spec:
  rules:
  - host: {{ $domain }}
    http:
      paths:
      - backend:
...
{{ end }}

# kubetpl r -s FQDNS=example.com,example2.com ...
```

* try to avoid separate `defaults` file (prefer https://github.com/shyiko/kubetpl/issues/10#issuecomment-425621647 <sup>btw, `# kubetpl:set:REPLICAS=1` can be used regardless of template `--syntax`</sup>).  
Having self-sufficient `testing.env`, `staging.env`, etc. proved to be easier to maintain & reason about (based of 1 year of experience / feedback from several dozen people managing hundreds of templates/envs).

**Comment by shaozi** [comment]
a quick note on the range example, as is, it gave me an error:

```
function "_" not defined
```

Add a `$` in front of `_` fixed it:

```
{{ range $_, $domain := splitList "," .FQDNS }}
```
